/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as LoginImport } from './routes/login'
import { Route as AppImport } from './routes/app'
import { Route as IndexImport } from './routes/index'
import { Route as AppProfileImport } from './routes/app.profile'
import { Route as AppPlaceholderImport } from './routes/app.placeholder'
import { Route as AppHomeImport } from './routes/app.home'
import { Route as AppGratitudeImport } from './routes/app.gratitude'
import { Route as AppCommunityImport } from './routes/app.community'

// Create/Update Routes

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppProfileRoute = AppProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)

const AppPlaceholderRoute = AppPlaceholderImport.update({
  id: '/placeholder',
  path: '/placeholder',
  getParentRoute: () => AppRoute,
} as any)

const AppHomeRoute = AppHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)

const AppGratitudeRoute = AppGratitudeImport.update({
  id: '/gratitude',
  path: '/gratitude',
  getParentRoute: () => AppRoute,
} as any)

const AppCommunityRoute = AppCommunityImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityImport
      parentRoute: typeof AppImport
    }
    '/app/gratitude': {
      id: '/app/gratitude'
      path: '/gratitude'
      fullPath: '/app/gratitude'
      preLoaderRoute: typeof AppGratitudeImport
      parentRoute: typeof AppImport
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeImport
      parentRoute: typeof AppImport
    }
    '/app/placeholder': {
      id: '/app/placeholder'
      path: '/placeholder'
      fullPath: '/app/placeholder'
      preLoaderRoute: typeof AppPlaceholderImport
      parentRoute: typeof AppImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppCommunityRoute: typeof AppCommunityRoute
  AppGratitudeRoute: typeof AppGratitudeRoute
  AppHomeRoute: typeof AppHomeRoute
  AppPlaceholderRoute: typeof AppPlaceholderRoute
  AppProfileRoute: typeof AppProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunityRoute: AppCommunityRoute,
  AppGratitudeRoute: AppGratitudeRoute,
  AppHomeRoute: AppHomeRoute,
  AppPlaceholderRoute: AppPlaceholderRoute,
  AppProfileRoute: AppProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/community': typeof AppCommunityRoute
  '/app/gratitude': typeof AppGratitudeRoute
  '/app/home': typeof AppHomeRoute
  '/app/placeholder': typeof AppPlaceholderRoute
  '/app/profile': typeof AppProfileRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/community': typeof AppCommunityRoute
  '/app/gratitude': typeof AppGratitudeRoute
  '/app/home': typeof AppHomeRoute
  '/app/placeholder': typeof AppPlaceholderRoute
  '/app/profile': typeof AppProfileRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/community': typeof AppCommunityRoute
  '/app/gratitude': typeof AppGratitudeRoute
  '/app/home': typeof AppHomeRoute
  '/app/placeholder': typeof AppPlaceholderRoute
  '/app/profile': typeof AppProfileRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/community'
    | '/app/gratitude'
    | '/app/home'
    | '/app/placeholder'
    | '/app/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/community'
    | '/app/gratitude'
    | '/app/home'
    | '/app/placeholder'
    | '/app/profile'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/community'
    | '/app/gratitude'
    | '/app/home'
    | '/app/placeholder'
    | '/app/profile'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app",
        "/login",
        "/onboarding"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/community",
        "/app/gratitude",
        "/app/home",
        "/app/placeholder",
        "/app/profile"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/app/community": {
      "filePath": "app.community.tsx",
      "parent": "/app"
    },
    "/app/gratitude": {
      "filePath": "app.gratitude.tsx",
      "parent": "/app"
    },
    "/app/home": {
      "filePath": "app.home.tsx",
      "parent": "/app"
    },
    "/app/placeholder": {
      "filePath": "app.placeholder.tsx",
      "parent": "/app"
    },
    "/app/profile": {
      "filePath": "app.profile.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
