/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TherapistImport } from './routes/therapist'
import { Route as StaffImport } from './routes/staff'
import { Route as ProfessionalImport } from './routes/professional'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as LoginImport } from './routes/login'
import { Route as AppImport } from './routes/app'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as AppWeeklyReviewImport } from './routes/app.weekly-review'
import { Route as AppProfileImport } from './routes/app.profile'
import { Route as AppProcessGoalImport } from './routes/app.process-goal'
import { Route as AppPlaceholderImport } from './routes/app.placeholder'
import { Route as AppHomeImport } from './routes/app.home'
import { Route as AppGratitudeImport } from './routes/app.gratitude'
import { Route as AppCommunityImport } from './routes/app.community'
import { Route as AppWorkshopWoopImport } from './routes/app.workshop.woop'
import { Route as AppWorkshopWarmupImport } from './routes/app.workshop.warmup'
import { Route as AppWorkshopLastDayImport } from './routes/app.workshop.last-day'
import { Route as AppWorkshopAuthenticSelfImport } from './routes/app.workshop.authentic-self'
import { Route as AppProModuleModuleIdImport } from './routes/app.pro-module.$moduleId'

// Create/Update Routes

const TherapistRoute = TherapistImport.update({
  id: '/therapist',
  path: '/therapist',
  getParentRoute: () => rootRoute,
} as any)

const StaffRoute = StaffImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRoute,
} as any)

const ProfessionalRoute = ProfessionalImport.update({
  id: '/professional',
  path: '/professional',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppWeeklyReviewRoute = AppWeeklyReviewImport.update({
  id: '/weekly-review',
  path: '/weekly-review',
  getParentRoute: () => AppRoute,
} as any)

const AppProfileRoute = AppProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)

const AppProcessGoalRoute = AppProcessGoalImport.update({
  id: '/process-goal',
  path: '/process-goal',
  getParentRoute: () => AppRoute,
} as any)

const AppPlaceholderRoute = AppPlaceholderImport.update({
  id: '/placeholder',
  path: '/placeholder',
  getParentRoute: () => AppRoute,
} as any)

const AppHomeRoute = AppHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)

const AppGratitudeRoute = AppGratitudeImport.update({
  id: '/gratitude',
  path: '/gratitude',
  getParentRoute: () => AppRoute,
} as any)

const AppCommunityRoute = AppCommunityImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)

const AppWorkshopWoopRoute = AppWorkshopWoopImport.update({
  id: '/workshop/woop',
  path: '/workshop/woop',
  getParentRoute: () => AppRoute,
} as any)

const AppWorkshopWarmupRoute = AppWorkshopWarmupImport.update({
  id: '/workshop/warmup',
  path: '/workshop/warmup',
  getParentRoute: () => AppRoute,
} as any)

const AppWorkshopLastDayRoute = AppWorkshopLastDayImport.update({
  id: '/workshop/last-day',
  path: '/workshop/last-day',
  getParentRoute: () => AppRoute,
} as any)

const AppWorkshopAuthenticSelfRoute = AppWorkshopAuthenticSelfImport.update({
  id: '/workshop/authentic-self',
  path: '/workshop/authentic-self',
  getParentRoute: () => AppRoute,
} as any)

const AppProModuleModuleIdRoute = AppProModuleModuleIdImport.update({
  id: '/pro-module/$moduleId',
  path: '/pro-module/$moduleId',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/professional': {
      id: '/professional'
      path: '/professional'
      fullPath: '/professional'
      preLoaderRoute: typeof ProfessionalImport
      parentRoute: typeof rootRoute
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffImport
      parentRoute: typeof rootRoute
    }
    '/therapist': {
      id: '/therapist'
      path: '/therapist'
      fullPath: '/therapist'
      preLoaderRoute: typeof TherapistImport
      parentRoute: typeof rootRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityImport
      parentRoute: typeof AppImport
    }
    '/app/gratitude': {
      id: '/app/gratitude'
      path: '/gratitude'
      fullPath: '/app/gratitude'
      preLoaderRoute: typeof AppGratitudeImport
      parentRoute: typeof AppImport
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeImport
      parentRoute: typeof AppImport
    }
    '/app/placeholder': {
      id: '/app/placeholder'
      path: '/placeholder'
      fullPath: '/app/placeholder'
      preLoaderRoute: typeof AppPlaceholderImport
      parentRoute: typeof AppImport
    }
    '/app/process-goal': {
      id: '/app/process-goal'
      path: '/process-goal'
      fullPath: '/app/process-goal'
      preLoaderRoute: typeof AppProcessGoalImport
      parentRoute: typeof AppImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileImport
      parentRoute: typeof AppImport
    }
    '/app/weekly-review': {
      id: '/app/weekly-review'
      path: '/weekly-review'
      fullPath: '/app/weekly-review'
      preLoaderRoute: typeof AppWeeklyReviewImport
      parentRoute: typeof AppImport
    }
    '/app/pro-module/$moduleId': {
      id: '/app/pro-module/$moduleId'
      path: '/pro-module/$moduleId'
      fullPath: '/app/pro-module/$moduleId'
      preLoaderRoute: typeof AppProModuleModuleIdImport
      parentRoute: typeof AppImport
    }
    '/app/workshop/authentic-self': {
      id: '/app/workshop/authentic-self'
      path: '/workshop/authentic-self'
      fullPath: '/app/workshop/authentic-self'
      preLoaderRoute: typeof AppWorkshopAuthenticSelfImport
      parentRoute: typeof AppImport
    }
    '/app/workshop/last-day': {
      id: '/app/workshop/last-day'
      path: '/workshop/last-day'
      fullPath: '/app/workshop/last-day'
      preLoaderRoute: typeof AppWorkshopLastDayImport
      parentRoute: typeof AppImport
    }
    '/app/workshop/warmup': {
      id: '/app/workshop/warmup'
      path: '/workshop/warmup'
      fullPath: '/app/workshop/warmup'
      preLoaderRoute: typeof AppWorkshopWarmupImport
      parentRoute: typeof AppImport
    }
    '/app/workshop/woop': {
      id: '/app/workshop/woop'
      path: '/workshop/woop'
      fullPath: '/app/workshop/woop'
      preLoaderRoute: typeof AppWorkshopWoopImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppCommunityRoute: typeof AppCommunityRoute
  AppGratitudeRoute: typeof AppGratitudeRoute
  AppHomeRoute: typeof AppHomeRoute
  AppPlaceholderRoute: typeof AppPlaceholderRoute
  AppProcessGoalRoute: typeof AppProcessGoalRoute
  AppProfileRoute: typeof AppProfileRoute
  AppWeeklyReviewRoute: typeof AppWeeklyReviewRoute
  AppProModuleModuleIdRoute: typeof AppProModuleModuleIdRoute
  AppWorkshopAuthenticSelfRoute: typeof AppWorkshopAuthenticSelfRoute
  AppWorkshopLastDayRoute: typeof AppWorkshopLastDayRoute
  AppWorkshopWarmupRoute: typeof AppWorkshopWarmupRoute
  AppWorkshopWoopRoute: typeof AppWorkshopWoopRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunityRoute: AppCommunityRoute,
  AppGratitudeRoute: AppGratitudeRoute,
  AppHomeRoute: AppHomeRoute,
  AppPlaceholderRoute: AppPlaceholderRoute,
  AppProcessGoalRoute: AppProcessGoalRoute,
  AppProfileRoute: AppProfileRoute,
  AppWeeklyReviewRoute: AppWeeklyReviewRoute,
  AppProModuleModuleIdRoute: AppProModuleModuleIdRoute,
  AppWorkshopAuthenticSelfRoute: AppWorkshopAuthenticSelfRoute,
  AppWorkshopLastDayRoute: AppWorkshopLastDayRoute,
  AppWorkshopWarmupRoute: AppWorkshopWarmupRoute,
  AppWorkshopWoopRoute: AppWorkshopWoopRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/professional': typeof ProfessionalRoute
  '/staff': typeof StaffRoute
  '/therapist': typeof TherapistRoute
  '/app/community': typeof AppCommunityRoute
  '/app/gratitude': typeof AppGratitudeRoute
  '/app/home': typeof AppHomeRoute
  '/app/placeholder': typeof AppPlaceholderRoute
  '/app/process-goal': typeof AppProcessGoalRoute
  '/app/profile': typeof AppProfileRoute
  '/app/weekly-review': typeof AppWeeklyReviewRoute
  '/app/pro-module/$moduleId': typeof AppProModuleModuleIdRoute
  '/app/workshop/authentic-self': typeof AppWorkshopAuthenticSelfRoute
  '/app/workshop/last-day': typeof AppWorkshopLastDayRoute
  '/app/workshop/warmup': typeof AppWorkshopWarmupRoute
  '/app/workshop/woop': typeof AppWorkshopWoopRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/professional': typeof ProfessionalRoute
  '/staff': typeof StaffRoute
  '/therapist': typeof TherapistRoute
  '/app/community': typeof AppCommunityRoute
  '/app/gratitude': typeof AppGratitudeRoute
  '/app/home': typeof AppHomeRoute
  '/app/placeholder': typeof AppPlaceholderRoute
  '/app/process-goal': typeof AppProcessGoalRoute
  '/app/profile': typeof AppProfileRoute
  '/app/weekly-review': typeof AppWeeklyReviewRoute
  '/app/pro-module/$moduleId': typeof AppProModuleModuleIdRoute
  '/app/workshop/authentic-self': typeof AppWorkshopAuthenticSelfRoute
  '/app/workshop/last-day': typeof AppWorkshopLastDayRoute
  '/app/workshop/warmup': typeof AppWorkshopWarmupRoute
  '/app/workshop/woop': typeof AppWorkshopWoopRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/professional': typeof ProfessionalRoute
  '/staff': typeof StaffRoute
  '/therapist': typeof TherapistRoute
  '/app/community': typeof AppCommunityRoute
  '/app/gratitude': typeof AppGratitudeRoute
  '/app/home': typeof AppHomeRoute
  '/app/placeholder': typeof AppPlaceholderRoute
  '/app/process-goal': typeof AppProcessGoalRoute
  '/app/profile': typeof AppProfileRoute
  '/app/weekly-review': typeof AppWeeklyReviewRoute
  '/app/pro-module/$moduleId': typeof AppProModuleModuleIdRoute
  '/app/workshop/authentic-self': typeof AppWorkshopAuthenticSelfRoute
  '/app/workshop/last-day': typeof AppWorkshopLastDayRoute
  '/app/workshop/warmup': typeof AppWorkshopWarmupRoute
  '/app/workshop/woop': typeof AppWorkshopWoopRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/professional'
    | '/staff'
    | '/therapist'
    | '/app/community'
    | '/app/gratitude'
    | '/app/home'
    | '/app/placeholder'
    | '/app/process-goal'
    | '/app/profile'
    | '/app/weekly-review'
    | '/app/pro-module/$moduleId'
    | '/app/workshop/authentic-self'
    | '/app/workshop/last-day'
    | '/app/workshop/warmup'
    | '/app/workshop/woop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/professional'
    | '/staff'
    | '/therapist'
    | '/app/community'
    | '/app/gratitude'
    | '/app/home'
    | '/app/placeholder'
    | '/app/process-goal'
    | '/app/profile'
    | '/app/weekly-review'
    | '/app/pro-module/$moduleId'
    | '/app/workshop/authentic-self'
    | '/app/workshop/last-day'
    | '/app/workshop/warmup'
    | '/app/workshop/woop'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/professional'
    | '/staff'
    | '/therapist'
    | '/app/community'
    | '/app/gratitude'
    | '/app/home'
    | '/app/placeholder'
    | '/app/process-goal'
    | '/app/profile'
    | '/app/weekly-review'
    | '/app/pro-module/$moduleId'
    | '/app/workshop/authentic-self'
    | '/app/workshop/last-day'
    | '/app/workshop/warmup'
    | '/app/workshop/woop'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfessionalRoute: typeof ProfessionalRoute
  StaffRoute: typeof StaffRoute
  TherapistRoute: typeof TherapistRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfessionalRoute: ProfessionalRoute,
  StaffRoute: StaffRoute,
  TherapistRoute: TherapistRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/app",
        "/login",
        "/onboarding",
        "/privacy",
        "/professional",
        "/staff",
        "/therapist"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/community",
        "/app/gratitude",
        "/app/home",
        "/app/placeholder",
        "/app/process-goal",
        "/app/profile",
        "/app/weekly-review",
        "/app/pro-module/$moduleId",
        "/app/workshop/authentic-self",
        "/app/workshop/last-day",
        "/app/workshop/warmup",
        "/app/workshop/woop"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/professional": {
      "filePath": "professional.tsx"
    },
    "/staff": {
      "filePath": "staff.tsx"
    },
    "/therapist": {
      "filePath": "therapist.tsx"
    },
    "/app/community": {
      "filePath": "app.community.tsx",
      "parent": "/app"
    },
    "/app/gratitude": {
      "filePath": "app.gratitude.tsx",
      "parent": "/app"
    },
    "/app/home": {
      "filePath": "app.home.tsx",
      "parent": "/app"
    },
    "/app/placeholder": {
      "filePath": "app.placeholder.tsx",
      "parent": "/app"
    },
    "/app/process-goal": {
      "filePath": "app.process-goal.tsx",
      "parent": "/app"
    },
    "/app/profile": {
      "filePath": "app.profile.tsx",
      "parent": "/app"
    },
    "/app/weekly-review": {
      "filePath": "app.weekly-review.tsx",
      "parent": "/app"
    },
    "/app/pro-module/$moduleId": {
      "filePath": "app.pro-module.$moduleId.tsx",
      "parent": "/app"
    },
    "/app/workshop/authentic-self": {
      "filePath": "app.workshop.authentic-self.tsx",
      "parent": "/app"
    },
    "/app/workshop/last-day": {
      "filePath": "app.workshop.last-day.tsx",
      "parent": "/app"
    },
    "/app/workshop/warmup": {
      "filePath": "app.workshop.warmup.tsx",
      "parent": "/app"
    },
    "/app/workshop/woop": {
      "filePath": "app.workshop.woop.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
